// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Phone string `json:"phone"`
	Pwd   string `json:"pwd"`
}

type LoginReq struct {
	User
}

type RegisterReq struct {
	User
}
